# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-15 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20180803_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymconfig',
            name='default_gym',
            field=models.ForeignKey(blank=True, help_text='Select the default gym for this installation. This will assign all new registered users to this gym and update all existing users without a gym.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.Gym', verbose_name='Default gym'),
        ),
    ]
