# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-21 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20180821_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='license_author',
        ),
        migrations.RemoveField(
            model_name='exerciseimage',
            name='license_author',
        ),
    ]
