# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-21 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_auto_20180821_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='license_author_link',
            new_name='license_author',
        ),
        migrations.RenameField(
            model_name='exerciseimage',
            old_name='license_author_link',
            new_name='license_author',
        ),
    ]
