# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 13:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_auto_20180815_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualMealItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, editable=False, verbose_name='Order')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Amount')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrition.Ingredient', verbose_name='Actual Ingredient')),
                ('meal', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='nutrition.Meal', verbose_name='Meal item')),
                ('weight_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrition.IngredientWeightUnit', verbose_name='Weight unit')),
            ],
        ),
    ]
