# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-21 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_ingredient_license_author_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='license_author',
        ),
    ]
