# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-21 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_remove_ingredient_license_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='license_author_link',
            new_name='license_author',
        ),
    ]
