# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 12:41
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20180815_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creating_user_id', models.IntegerField(default=1, help_text='Id of the user creating another user through the application', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Id for user creatig ')),
                ('api_created_flag', models.BooleanField(default=True, editable=False)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='create_users_api',
            field=models.IntegerField(default=-1, help_text='Allow external creation of users through the api', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name='Allow external creation of users'),
        ),
    ]
