# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-23 11:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180816_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysofweek',
            name='training_cycle',
            field=models.CharField(choices=[('microcycle', 'Micro'), ('mesocycle', 'Meso'), ('macrocycle', 'Macro')], default='microcycle', max_length=10),
        ),
        migrations.AlterField(
            model_name='userapi',
            name='creating_user_id',
            field=models.IntegerField(default=1, help_text='Id of the user creating another user         through the application', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Id for user creating '),
        ),
    ]
