# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-24 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180824_0954'),
        ('core', '0016_merge'),
    ]

    operations = [
    ]
