# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-29 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseauthor',
            name='author_name',
            field=models.CharField(help_text='If you are not the author, enter the name or source here. This is needed for some licenses e.g. the CC-BY-SA.', max_length=60, verbose_name='Author Name'),
        ),
    ]
