# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_workoutlog_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='dropset',
            field=models.BooleanField(default=False, verbose_name='drop set'),
        ),
    ]
