# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-24 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_set_dropset'),
        ('manager', '0012_workout_cycle_kind'),
    ]

    operations = [
    ]
